language: java
jdk:
- openjdk8
deploy:
  provider: heroku
  api_key:
    secure: SxRgjblvlhLk2ykhi74prOPNzdEum1Tg+HuF147PsgUzJZ5dgfmBFBFgngVwTzuttRYdjOm4dqBjTiezfPd6/4SI4Iurt48gur55dP1otqaKbtr7PHBvftBxIjmEuoe2w745GDCMv+WjjCX89SZCxpEbXym8FT+IHOOjcD031kNLx57QN0Y/mmeRhCGN8e9G9C09KSed8dQ1bo2BNXfkHFvTrHGm5vkStGNdSa1flIXy3xK6msuK9gS5lOd+24OQFYDPmpEoS8L+PUnahD1JOO1jIJ/DOpNUeIcNQUZdPB2TVNIIdSXN3graEgy17Z/b8b7WIttzUZzYb+VF5b3qzVqsHiQRMQn6V885R9yMi3dauQV3OdYp+Cg3TB16tDnvQt8yjfin+omYWfONyDD8tRJgson8YckhRO8CGRrySmKImvja2O8/3IooQpeI6VVNcy3NwygYwGY7yF0As4//vtUBU/a+0CJZYwxIWND1rl6sI2Avi6C2zBYVrroPwm1SdfH8+09upvzlg+aRAGSUq+aFv993n3arOKuqcxkWahpGdcsWKOfXlGYB6RhyPONVqBuPBvR+2AECiiNgVwW/iiCKiBAhyCX+2mP0tWlqzAALeGXHsuxCLVxzexrAMG88eRpvkWfFQBenSFshzremBRMvgyq8sq8v0PiRB+qBDjo=
  app: soulradio
  on:
    repo: alakijaayo/SoulRadio