language: java
jdk:
- openjdk8
deploy:
  provider: heroku
  api_key:
    secure: XTfK+5jrncHoGliFvcWC4hponlhhAZMe0BCDsagai3XtyODoFEJltPvNY0I/Yt2Pc6nPdzcYtEX61Af8rLpP7AZFtPnhMGmpieqLSZ+rYxFHPVAIk+6/w+k35Q6BdBqja/kCzp5Ku6h8jAqXhRhqEjlcS6o9ZFCouOT2T3I64lgUpzs//4oDy2B9316gdkNlW6ucTBXUovytFj6X2R/FDe+EVbYGZvrL3vjeJs70hOpiI4sIx9HTuY9WgAvBDw2MSuiWoZbh1vMxoPpyFKh332pZbSAtVT4WaGhDaV48SaacB6NODQ1ziH4XzoNHf2GiGRaOzUPBstYou0Tg6EshwX2go73Waslg4FCnoGxGqJw2Hz19f7Z3EYHD1nefctka2JpyeFe1BObVMkoiwk62EQ/ltpHRmrGJbCjScmiBGRP3fuYb4byvZF8rcvLy7FgtMGZuVK2yqSfrkYJkzwfuDfuSKtiYztsmsOqYDnVeYyzT3q42s8QPJHsLVVXJ8jlgsvSPQAzbe0LgZvEuYy2loqXT3bGSnl+ViiJDZrWRSoM37xA3wjcEfsgBUIiN7UjjwvUaolg35tPWkEO2L97WzY17zy5OgWWLX75p+Fz75XkkQT3RksezVpBBSAxJQkW1QMBA8UPktA11SSEfL84PQvNqPbrejPlc5XUARvfKrsg=
  app: soulradio
  on:
    repo: alakijaayo/SoulRadio
